base_url = "https://animeshz.github.io/site"
output_dir = ".build"
build_search_index = true

[markdown]
highlight_code = true

[link_checker]
internal_level = "warn"
external_level = "error"

[extra]
# Put all your custom variables here
