name: Deploy on GH Pages

on:
 push:
  branches:
   - main

jobs:
  build:

    name: Publish site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0

      - name: Setup Yarn & Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Build TailwindCSS
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          OUT_DIR: .build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
